modLoader="javafml"
loaderVersion="[1,)"
license="MIT (CC BY-NC-SA 4.0 for some Assets)"
issueTrackerURL="https://github.com/quiqueck/BetterEnd/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Better End"
description="More content for The End dimension, including new biomes, plants, mobs, mechanics, terrain generation and more."
authors="quiqueck, paulevs (original author), Bulldog83, Edos, Yuki, Seaward, Firel"
displayURL="https://www.curseforge.com/minecraft/mc-mods/betterend"
logoFile="assets/betterend/icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bclib"
mandatory=true
versionRange="[${bclib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wover"
mandatory=true
versionRange="[${wover_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wunderlib"
mandatory=true
versionRange="[${wunderlib_version},)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="betterend.mixins.common.json"

[[mixins]]
config="betterend.mixins.client.json"

[modproperties.${mod_id}]
updater_icon="icon_updater.png"

[modproperties.${mod_id}.downloads]
modrinth="https://modrinth.com/mod/betterend"
curseforge="https://www.curseforge.com/minecraft/mc-mods/betterend"

[modproperties.${mod_id}.modupdater]
strategy="curseforge"
projectID=413596
